### ISSUE TITLE
'SysInterrupt_TIM3_Update' was not declared in this scope

### ISSUE THREAD

**Issue by yaneexy** [pkourany/PulseSensor_Spark#1]
Veryfing code using this library in Particle Build fails with this error:

```
PulseSensor_Spark/SparkIntervalTimer.h:128:30: error: 'SysInterrupt_TIM3_Update' was not declared in this scope
   if (!attachSystemInterrupt(SysInterrupt_TIM3_Update, Wiring_TIM3_Interrupt_Handler_override)) 
```

**Comment by pkourany** [comment]
@yaneexy, the SparkIntervalTimer code is slightly outdated.  I will remove it from the library and require that the (newer) IDE library be attached to the app.   That way it will always be up to date.   I'll publish an updated PulseSensor library to the IDE shortly.  Thanks for pointing this out.

**Comment by pkourany** [comment]
The updated Build library is now available!
