### ISSUE TITLE
'SysInterrupt_TIM2' was not declared in this scope

### ISSUE THREAD

**Issue by sebastianrmirz** [pkourany/PulseSensor_Spark#2]
Veryfing code using this library in Particle Build fails with this error:

```
PulseSensor_Spark/SparkIntervalTimer.h:121:30: error: 'SysInterrupt_TIM2' was not declared in this scope
   if (!attachSystemInterrupt(SysInterrupt_TIM2, Wiring_TIM2_Interrupt_Handler_override)) 
```

**Comment by nurstcor** [comment]
PulseSensor_Spark/SparkIntervalTimer.h:121:30: error: 'SysInterrupt_TIM2' was not declared in this scope
   if (!attachSystemInterrupt(SysInterrupt_TIM2, Wiring_TIM2_Interrupt_Handler_override))
